"""Add CRM AI metadata fields

Revision ID: 18b33edaa0be
Revises: 68eca2beaf79
Create Date: 2026-08-10 05:14:27.645495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18b33edaa0be'
down_revision: Union[str, None] = '68eca2beaf79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_deals', sa.Column('lead_score', sa.Integer(), nullable=True))
    op.add_column('crm_deals', sa.Column('intent_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('crm_deals', sa.Column('last_scored_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_crm_deals_org_lead_score', 'crm_deals', ['organization_id', 'lead_score'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crm_deals_org_lead_score', table_name='crm_deals', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_column('crm_deals', 'last_scored_at')
    op.drop_column('crm_deals', 'intent_signals')
    op.drop_column('crm_deals', 'lead_score')
    # ### end Alembic commands ###
