"""Add OrganizationDocument with pgvector

Revision ID: 2673de053bfc
Revises: bea242b89e37
Create Date: 2026-08-06 11:06:46.851658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2673de053bfc'
down_revision: Union[str, None] = 'bea242b89e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
