"""Add stripe billing fields to organizations

Revision ID: bea242b89e37
Revises: ea0a156f1b08
Create Date: 2026-08-06 04:07:33.321768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea242b89e37'
down_revision: Union[str, None] = 'ea0a156f1b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('subscription_tier', sa.String(length=20), server_default='FREE', nullable=False))
    op.add_column('organizations', sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('gstin', sa.String(length=15), nullable=True))
    op.add_column('organizations', sa.Column('billing_state', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('ai_credits_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('organizations', sa.Column('bonus_ai_credits', sa.Integer(), server_default='0', nullable=False))
    op.add_column('organizations', sa.Column('last_billing_event_ts', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('organizations', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'FREE'::character varying"))
    op.create_index(op.f('ix_organizations_stripe_customer_id'), 'organizations', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_organizations_stripe_subscription_id'), 'organizations', ['stripe_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_stripe_subscription_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_stripe_customer_id'), table_name='organizations')
    op.alter_column('organizations', 'subscription_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'FREE'::character varying"))
    op.drop_column('organizations', 'last_billing_event_ts')
    op.drop_column('organizations', 'bonus_ai_credits')
    op.drop_column('organizations', 'ai_credits_used')
    op.drop_column('organizations', 'billing_state')
    op.drop_column('organizations', 'gstin')
    op.drop_column('organizations', 'stripe_subscription_id')
    op.drop_column('organizations', 'stripe_customer_id')
    op.drop_column('organizations', 'subscription_tier')
    # ### end Alembic commands ###
