"""Add OrganizationDocument with pgvector

Revision ID: fcca3e2f9e5e
Revises: 2673de053bfc
Create Date: 2026-08-06 11:09:33.458532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcca3e2f9e5e'
down_revision: Union[str, None] = '2673de053bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
